"""Minimal persistence contracts for the future authentication phase."""
from __future__ import annotations
from typing import Protocol
from uuid import UUID
from .models import Project, ProjectMembership, User
class UserRepository(Protocol):
    def create(self,user:User)->User: ...
    def get_by_id(self,user_id:UUID)->User|None: ...
    def get_by_username(self,username:str)->User|None: ...
    def get_by_email(self,email:str)->User|None: ...
class ProjectMembershipRepository(Protocol):
    def add(self,membership:ProjectMembership)->ProjectMembership: ...
    def list_for_user(self,user_id:UUID)->list[ProjectMembership]: ...
    def has_access(self,user_id:UUID,project_id:str)->bool: ...


class ProjectRepository(Protocol):
    def create(self, project: Project) -> Project: ...
    def create_with_owner(
            self,
            project: Project,
            membership: ProjectMembership,
    ) -> Project: ...
    def get_by_id(self, project_id: str) -> Project | None: ...
    def list_for_user(self, user_id: UUID) -> list[Project]: ...
